name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy to the server
      - name: Connect to server
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan 35.239.219.217 >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh -tt lucasnarloch123@35.239.219.217 
          EOF

      - name: Deploy
        run: |
          cd Coming-Back-Node
          git pull --rebase origin main
          sudo docker-compose down
          sudo npm run install-all
          sudo docker-compose up -d --build
          EOF
